using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HOHO18.Common
{
    public class FileContentType
    {        
        public const string f = "application/octet-stream";//这是个*号
        public const string f001 = "application/x-001";
        public const string f301 = "application/x-301";
        public const string f323 = "text/h323";
        public const string f906 = "application/x-906";
        public const string f907 = "drawing/907";
        public const string fa11 = "application/x-a11";
        public const string facp = "audio/x-mei-aac";
        public const string fai = "application/postscript";
        public const string faif = "audio/aiff";
        public const string faifc = "audio/aiff";
        public const string faiff = "audio/aiff";
        public const string fanv = "application/x-anv";
        public const string fasa = "text/asa";
        public const string fasf = "video/x-ms-asf";
        public const string fasp = "text/asp";
        public const string fasx = "video/x-ms-asf";
        public const string fau = "audio/basic";
        public const string favi = "video/avi";
        public const string fawf = "application/vnd.adobe.workflow";
        public const string fbiz = "text/xml";
        public const string fbmp = "application/x-bmp";
        public const string fbot = "application/x-bot";
        public const string fc4t = "application/x-c4t";
        public const string fc90 = "application/x-c90";
        public const string fcal = "application/x-cals";
        public const string fcat = "application/vnd.ms-pki.seccat";
        public const string fcdf = "application/x-netcdf";
        public const string fcdr = "application/x-cdr";
        public const string fcel = "application/x-cel";
        public const string fcer = "application/x-x509-ca-cert";
        public const string fcg4 = "application/x-g4";
        public const string fcgm = "application/x-cgm";
        public const string fcit = "application/x-cit";
        public const string fclass = "java/*";
        public const string fcml = "text/xml";
        public const string fcmp = "application/x-cmp";
        public const string fcmx = "application/x-cmx";
        public const string fcot = "application/x-cot";
        public const string fcrl = "application/pkix-crl";
        public const string fcrt = "application/x-x509-ca-cert";
        public const string fcsi = "application/x-csi";
        public const string fcss = "text/css";
        public const string fcut = "application/x-cut";
        public const string fdbf = "application/x-dbf";
        public const string fdbm = "application/x-dbm";
        public const string fdbx = "application/x-dbx";
        public const string fdcd = "text/xml";
        public const string fdcx = "application/x-dcx";
        public const string fder = "application/x-x509-ca-cert";
        public const string fdgn = "application/x-dgn";
        public const string fdib = "application/x-dib";
        public const string fdll = "application/x-msdownload";
        public const string fdoc = "application/msword";
        public const string fdot = "application/msword";
        public const string fdrw = "application/x-drw";
        public const string fdtd = "text/xml";
        //public const string fdwf = "Model/vnd.dwf";
        public const string fdwf = "application/x-dwf";
        public const string fdwg = "application/x-dwg";
        public const string fdxb = "application/x-dxb";
        public const string fdxf = "application/x-dxf";
        public const string fedn = "application/vnd.adobe.edn";
        public const string femf = "application/x-emf";
        public const string feml = "message/rfc822";
        public const string fent = "text/xml";
        public const string fepi = "application/x-epi";
        public const string feps = "application/x-ps";
        //public const string feps = "application/postscript";
        public const string fetd = "application/x-ebx";
        public const string fexe = "application/x-msdownload";
        public const string ffax = "image/fax";
        public const string ffdf = "application/vnd.fdf";
        public const string ffif = "application/fractals";
        public const string ffo = "text/xml";
        public const string ffrm = "application/x-frm";
        public const string fg4 = "application/x-g4";
        public const string fgbr = "application/x-gbr";
        public const string fgcd = "application/x-gcd";
        public const string fgif = "image/gif";
        public const string fgl2 = "application/x-gl2";
        public const string fgp4 = "application/x-gp4";
        public const string fhgl = "application/x-hgl";
        public const string fhmr = "application/x-hmr";
        public const string fhpg = "application/x-hpgl";
        public const string fhpl = "application/x-hpl";
        public const string fhqx = "application/mac-binhex40";
        public const string fhrf = "application/x-hrf";
        public const string fhta = "application/hta";
        public const string fhtc = "text/x-component";
        public const string fhtm = "text/html";
        public const string fhtml = "text/html";
        public const string fhtt = "text/webviewhtml";
        public const string fhtx = "text/html";
        public const string ficb = "application/x-icb";
        //public const string fico = "image/x-icon";
        public const string fico = "application/x-ico";
        public const string fiff = "application/x-iff";
        public const string fig4 = "application/x-g4";
        public const string figs = "application/x-igs";
        public const string fiii = "application/x-iphone";
        public const string fimg = "application/x-img";
        public const string fins = "application/x-internet-signup";
        public const string fisp = "application/x-internet-signup";
        public const string fIVF = "video/x-ivf";
        public const string fjava = "java/*";
        public const string fjfif = "image/jpeg";
        //public const string fjpe = "image/jpeg";
        public const string fjpe = "application/x-jpe";
        public const string fjpeg = "image/jpeg";
        //public const string fjpg = "image/jpeg";
        public const string fjpg = "application/x-jpg";
        public const string fjs = "application/x-javascript";
        public const string fjsp = "text/html";
        public const string fla1 = "audio/x-liquid-file";
        public const string flar = "application/x-laplayer-reg";
        public const string flatex = "application/x-latex";
        public const string flavs = "audio/x-liquid-secure";
        public const string flbm = "application/x-lbm";
        public const string flmsff = "audio/x-la-lms";
        public const string fls = "application/x-javascript";
        public const string fltr = "application/x-ltr";
        public const string fm1v = "video/x-mpeg";
        public const string fm2v = "video/x-mpeg";
        public const string fm3u = "audio/mpegurl";
        public const string fm4e = "video/mpeg4";
        public const string fmac = "application/x-mac";
        public const string fman = "application/x-troff-man";
        public const string fmath = "text/xml";
        public const string fmdb = "application/msaccess";
        //public const string fmdb = "application/x-mdb";
        public const string fmfp = "application/x-shockwave-flash";
        public const string fmht = "message/rfc822";
        public const string fmhtml = "message/rfc822";
        public const string fmi = "application/x-mi";
        public const string fmid = "audio/mid";
        public const string fmidi = "audio/mid";
        public const string fmil = "application/x-mil";
        public const string fmml = "text/xml";
        public const string fmnd = "audio/x-musicnet-download";
        public const string fmns = "audio/x-musicnet-stream";
        public const string fmocha = "application/x-javascript";
        public const string fmovie = "video/x-sgi-movie";
        public const string fmp1 = "audio/mp1";
        public const string fmp2 = "audio/mp2";
        public const string fmp2v = "video/mpeg";
        public const string fmp3 = "audio/mp3";
        public const string fmp4 = "video/mpeg4";
        public const string fmpa = "video/x-mpg";
        public const string fmpd = "application/vnd.ms-project";
        public const string fmpe = "video/x-mpeg";
        public const string fmpeg = "video/mpg";
        public const string fmpg = "video/mpg";
        public const string fmpga = "audio/rn-mpeg";
        public const string fmpp = "application/vnd.ms-project";
        public const string fmps = "video/x-mpeg";
        public const string fmpt = "application/vnd.ms-project";
        public const string fmpv = "video/mpg";
        public const string fmpv2 = "video/mpeg";
        public const string fmpw = "application/vnd.ms-project";
        public const string fmpx = "application/vnd.ms-project";
        public const string fmtx = "text/xml";
        public const string fmxp = "application/x-mmxp";
        public const string fnet = "image/pnetvue";
        public const string fnrf = "application/x-nrf";
        public const string fnws = "message/rfc822";
        public const string fodc = "text/x-ms-odc";
        public const string fout = "application/x-out";
        public const string fp10 = "application/pkcs10";
        public const string fp12 = "application/x-pkcs12";
        public const string fp7b = "application/x-pkcs7-certificates";
        public const string fp7c = "application/pkcs7-mime";
        public const string fp7m = "application/pkcs7-mime";
        public const string fp7r = "application/x-pkcs7-certreqresp";
        public const string fp7s = "application/pkcs7-signature";
        public const string fpc5 = "application/x-pc5";
        public const string fpci = "application/x-pci";
        public const string fpcl = "application/x-pcl";
        public const string fpcx = "application/x-pcx";
        public const string fpdf = "application/pdf";
        //public const string fpdf = "application/pdf";
        public const string fpdx = "application/vnd.adobe.pdx";
        public const string fpfx = "application/x-pkcs12";
        public const string fpgl = "application/x-pgl";
        public const string fpic = "application/x-pic";
        public const string fpko = "application/vnd.ms-pki.pko";
        public const string fpl = "application/x-perl";
        public const string fplg = "text/html";
        public const string fpls = "audio/scpls";
        public const string fplt = "application/x-plt";
        //public const string fpng = "image/png";
        public const string fpng = "application/x-png";
        public const string fpot = "application/vnd.ms-powerpoint";
        public const string fppa = "application/vnd.ms-powerpoint";
        public const string fppm = "application/x-ppm";
        public const string fpps = "application/vnd.ms-powerpoint";
        public const string fppt = "application/vnd.ms-powerpoint";
        //public const string fppt = "application/x-ppt";
        public const string fpr = "application/x-pr";
        public const string fprf = "application/pics-rules";
        public const string fprn = "application/x-prn";
        public const string fprt = "application/x-prt";
        public const string fps = "application/x-ps";
        //public const string fps = "application/postscript";
        public const string fptn = "application/x-ptn";
        public const string fpwz = "application/vnd.ms-powerpoint";
        public const string fr3t = "text/vnd.rn-realtext3d";
        public const string fra = "audio/vnd.rn-realaudio";
        public const string fram = "audio/x-pn-realaudio";
        public const string fras = "application/x-ras";
        public const string frat = "application/rat-file";
        public const string frdf = "text/xml";
        public const string frec = "application/vnd.rn-recording";
        public const string fred = "application/x-red";
        public const string frgb = "application/x-rgb";
        public const string frjs = "application/vnd.rn-realsystem-rjs";
        public const string frjt = "application/vnd.rn-realsystem-rjt";
        public const string frlc = "application/x-rlc";
        public const string frle = "application/x-rle";
        public const string frm = "application/vnd.rn-realmedia";
        public const string frmf = "application/vnd.adobe.rmf";
        public const string frmi = "audio/mid";
        public const string frmj = "application/vnd.rn-realsystem-rmj";
        public const string frmm = "audio/x-pn-realaudio";
        public const string frmp = "application/vnd.rn-rn_music_package";
        public const string frms = "application/vnd.rn-realmedia-secure";
        public const string frmvb = "application/vnd.rn-realmedia-vbr";
        public const string frmx = "application/vnd.rn-realsystem-rmx";
        public const string frnx = "application/vnd.rn-realplayer";
        public const string frp = "image/vnd.rn-realpix";
        public const string frpm = "audio/x-pn-realaudio-plugin";
        public const string frsml = "application/vnd.rn-rsml";
        public const string frt = "text/vnd.rn-realtext";
        public const string frtf = "application/msword";
        //public const string frtf = "application/x-rtf";
        public const string frv = "video/vnd.rn-realvideo";
        public const string fsam = "application/x-sam";
        public const string fsat = "application/x-sat";
        public const string fsdp = "application/sdp";
        public const string fsdw = "application/x-sdw";
        public const string fsit = "application/x-stuffit";
        public const string fslb = "application/x-slb";
        public const string fsld = "application/x-sld";
        public const string fslk = "drawing/x-slk";
        public const string fsmi = "application/smil";
        public const string fsmil = "application/smil";
        public const string fsmk = "application/x-smk";
        public const string fsnd = "audio/basic";
        public const string fsol = "text/plain";
        public const string fsor = "text/plain";
        public const string fspc = "application/x-pkcs7-certificates";
        public const string fspl = "application/futuresplash";
        public const string fspp = "text/xml";
        public const string fssm = "application/streamingmedia";
        public const string fsst = "application/vnd.ms-pki.certstore";
        public const string fstl = "application/vnd.ms-pki.stl";
        public const string fstm = "text/html";
        public const string fsty = "application/x-sty";
        public const string fsvg = "text/xml";
        public const string fswf = "application/x-shockwave-flash";
        public const string ftdf = "application/x-tdf";
        public const string ftg4 = "application/x-tg4";
        public const string ftga = "application/x-tga";
        //public const string ftif = "image/tiff";
        public const string ftif = "application/x-tif";
        public const string ftiff = "image/tiff";
        public const string ftld = "text/xml";
        public const string ftop = "drawing/x-top";
        public const string ftorrent = ";application/x-bittorrent";
        public const string ftsd = "text/xml";
        public const string ftxt = "text/plain";
        public const string fuin = "application/x-icq";
        public const string fuls = "text/iuls";
        public const string fvcf = "text/x-vcard";
        public const string fvda = "application/x-vda";
        public const string fvdx = "application/vnd.visio";
        public const string fvml = "text/xml";
        public const string fvpg = "application/x-vpeg005";
        //public const string fvsd = "application/vnd.visio";
        public const string fvsd = "application/x-vsd";
        public const string fvss = "application/vnd.visio";
        //public const string fvst = "application/vnd.visio";
        public const string fvst = "application/x-vst";
        public const string fvsw = "application/vnd.visio";
        public const string fvsx = "application/vnd.visio";
        public const string fvtx = "application/vnd.visio";
        public const string fvxml = "text/xml";
        public const string fwav = "audio/wav";
        public const string fwax = "audio/x-ms-wax";
        public const string fwb1 = "application/x-wb1";
        public const string fwb2 = "application/x-wb2";
        public const string fwb3 = "application/x-wb3";
        public const string fwbmp = "image/vnd.wap.wbmp";
        public const string fwiz = "application/msword";
        public const string fwk3 = "application/x-wk3";
        public const string fwk4 = "application/x-wk4";
        public const string fwkq = "application/x-wkq";
        public const string fwks = "application/x-wks";
        public const string fwm = "video/x-ms-wm";
        public const string fwma = "audio/x-ms-wma";
        public const string fwmd = "application/x-ms-wmd";
        public const string fwmf = "application/x-wmf";
        public const string fwml = "text/vnd.wap.wml";
        public const string fwmv = "video/x-ms-wmv";
        public const string fwmx = "video/x-ms-wmx";
        public const string fwmz = "application/x-ms-wmz";
        public const string fwp6 = "application/x-wp6";
        public const string fwpd = "application/x-wpd";
        public const string fwpg = "application/x-wpg";
        public const string fwpl = "application/vnd.ms-wpl";
        //public const string fwq1 = "application/x-wq1";
        public const string fwr1 = "application/x-wr1";
        public const string fwri = "application/x-wri";
        public const string fwrk = "application/x-wrk";
        public const string fws = "application/x-ws";
        public const string fws2 = "application/x-ws";
        public const string fwsc = "text/scriptlet";
        public const string fwsdl = "text/xml";
        public const string fwvx = "video/x-ms-wvx";
        public const string fxdp = "application/vnd.adobe.xdp";
        public const string fxdr = "text/xml";
        public const string fxfd = "application/vnd.adobe.xfd";
        public const string fxfdf = "application/vnd.adobe.xfdf";
        public const string fxhtml = "text/html";
        public const string fxls = "application/vnd.ms-excel";
        //public const string fxls = "application/x-xls";
        public const string fxlw = "application/x-xlw";
        public const string fxml = "text/xml";
        public const string fxpl = "audio/scpls";
        public const string fxq = "text/xml";
        public const string fxql = "text/xml";
        public const string fxquery = "text/xml";
        public const string fxsd = "text/xml";
        public const string fxsl = "text/xml";
        public const string fxslt = "text/xml";
        public const string fxwd = "application/x-xwd";
        public const string fx_b = "application/x-x_b";
        public const string fx_t = "application/x-x_t";

        /// <summary>
        /// 文件后缀名和ContentType键值对
        /// </summary>
        /// <returns></returns>
        public Dictionary<string, string> fileDictionary()
        {
            Dictionary<string, string> fDictionary = new Dictionary<string, string>();

            fDictionary.Add("*", "application/octet-stream");//这是个*号
            fDictionary.Add("001", "application/x-001");
            fDictionary.Add("301", "application/x-301");
            fDictionary.Add("323", "text/h323");
            fDictionary.Add("906", "application/x-906");
            fDictionary.Add("907", "drawing/907");
            fDictionary.Add("a11", "application/x-a11");
            fDictionary.Add("acp", "audio/x-mei-aac");
            fDictionary.Add("ai", "application/postscript");
            fDictionary.Add("aif", "audio/aiff");
            fDictionary.Add("aifc", "audio/aiff");
            fDictionary.Add("aiff", "audio/aiff");
            fDictionary.Add("anv", "application/x-anv");
            fDictionary.Add("asa", "text/asa");
            fDictionary.Add("asf", "video/x-ms-asf");
            fDictionary.Add("asp", "text/asp");
            fDictionary.Add("asx", "video/x-ms-asf");
            fDictionary.Add("au", "audio/basic");
            fDictionary.Add("avi", "video/avi");
            fDictionary.Add("awf", "application/vnd.adobe.workflow");
            fDictionary.Add("biz", "text/xml");
            fDictionary.Add("bmp", "application/x-bmp");
            fDictionary.Add("bot", "application/x-bot");
            fDictionary.Add("c4t", "application/x-c4t");
            fDictionary.Add("c90", "application/x-c90");
            fDictionary.Add("cal", "application/x-cals");
            fDictionary.Add("cat", "application/vnd.ms-pki.seccat");
            fDictionary.Add("cdf", "application/x-netcdf");
            fDictionary.Add("cdr", "application/x-cdr");
            fDictionary.Add("cel", "application/x-cel");
            fDictionary.Add("cer", "application/x-x509-ca-cert");
            fDictionary.Add("cg4", "application/x-g4");
            fDictionary.Add("cgm", "application/x-cgm");
            fDictionary.Add("cit", "application/x-cit");
            fDictionary.Add("class", "java/*");
            fDictionary.Add("cml", "text/xml");
            fDictionary.Add("cmp", "application/x-cmp");
            fDictionary.Add("cmx", "application/x-cmx");
            fDictionary.Add("cot", "application/x-cot");
            fDictionary.Add("crl", "application/pkix-crl");
            fDictionary.Add("crt", "application/x-x509-ca-cert");
            fDictionary.Add("csi", "application/x-csi");
            fDictionary.Add("css", "text/css");
            fDictionary.Add("cut", "application/x-cut");
            fDictionary.Add("dbf", "application/x-dbf");
            fDictionary.Add("dbm", "application/x-dbm");
            fDictionary.Add("dbx", "application/x-dbx");
            fDictionary.Add("dcd", "text/xml");
            fDictionary.Add("dcx", "application/x-dcx");
            fDictionary.Add("der", "application/x-x509-ca-cert");
            fDictionary.Add("dgn", "application/x-dgn");
            fDictionary.Add("dib", "application/x-dib");
            fDictionary.Add("dll", "application/x-msdownload");
            fDictionary.Add("doc", "application/msword");
            fDictionary.Add("dot", "application/msword");
            fDictionary.Add("drw", "application/x-drw");
            fDictionary.Add("dtd", "text/xml");
            //fDictionary.Add("dwf", "Model/vnd.dwf");
            fDictionary.Add("dwf", "application/x-dwf");
            fDictionary.Add("dwg", "application/x-dwg");
            fDictionary.Add("dxb", "application/x-dxb");
            fDictionary.Add("dxf", "application/x-dxf");
            fDictionary.Add("edn", "application/vnd.adobe.edn");
            fDictionary.Add("emf", "application/x-emf");
            fDictionary.Add("eml", "message/rfc822");
            fDictionary.Add("ent", "text/xml");
            fDictionary.Add("epi", "application/x-epi");
            fDictionary.Add("eps", "application/x-ps");
            //fDictionary.Add("eps", "application/postscript");
            fDictionary.Add("etd", "application/x-ebx");
            fDictionary.Add("exe", "application/x-msdownload");
            fDictionary.Add("fax", "image/fax");
            fDictionary.Add("fdf", "application/vnd.fdf");
            fDictionary.Add("fif", "application/fractals");
            fDictionary.Add("fo", "text/xml");
            fDictionary.Add("frm", "application/x-frm");
            fDictionary.Add("g4", "application/x-g4");
            fDictionary.Add("gbr", "application/x-gbr");
            fDictionary.Add("gcd", "application/x-gcd");
            fDictionary.Add("gif", "image/gif");
            fDictionary.Add("gl2", "application/x-gl2");
            fDictionary.Add("gp4", "application/x-gp4");
            fDictionary.Add("hgl", "application/x-hgl");
            fDictionary.Add("hmr", "application/x-hmr");
            fDictionary.Add("hpg", "application/x-hpgl");
            fDictionary.Add("hpl", "application/x-hpl");
            fDictionary.Add("hqx", "application/mac-binhex40");
            fDictionary.Add("hrf", "application/x-hrf");
            fDictionary.Add("hta", "application/hta");
            fDictionary.Add("htc", "text/x-component");
            fDictionary.Add("htm", "text/html");
            fDictionary.Add("html", "text/html");
            fDictionary.Add("htt", "text/webviewhtml");
            fDictionary.Add("htx", "text/html");
            fDictionary.Add("icb", "application/x-icb");
            //fDictionary.Add("ico", "image/x-icon");
            fDictionary.Add("ico", "application/x-ico");
            fDictionary.Add("iff", "application/x-iff");
            fDictionary.Add("ig4", "application/x-g4");
            fDictionary.Add("igs", "application/x-igs");
            fDictionary.Add("iii", "application/x-iphone");
            fDictionary.Add("img", "application/x-img");
            fDictionary.Add("ins", "application/x-internet-signup");
            fDictionary.Add("isp", "application/x-internet-signup");
            fDictionary.Add("IVF", "video/x-ivf");
            fDictionary.Add("java", "java/*");
            fDictionary.Add("jfif", "image/jpeg");
            //fDictionary.Add("jpe", "image/jpeg");
            fDictionary.Add("jpe", "application/x-jpe");
            fDictionary.Add("jpeg", "image/jpeg");
            //fDictionary.Add("jpg", "image/jpeg");
            fDictionary.Add("jpg", "application/x-jpg");
            fDictionary.Add("js", "application/x-javascript");
            fDictionary.Add("jsp", "text/html");
            fDictionary.Add("la1", "audio/x-liquid-file");
            fDictionary.Add("lar", "application/x-laplayer-reg");
            fDictionary.Add("latex", "application/x-latex");
            fDictionary.Add("lavs", "audio/x-liquid-secure");
            fDictionary.Add("lbm", "application/x-lbm");
            fDictionary.Add("lmsff", "audio/x-la-lms");
            fDictionary.Add("ls", "application/x-javascript");
            fDictionary.Add("ltr", "application/x-ltr");
            fDictionary.Add("m1v", "video/x-mpeg");
            fDictionary.Add("m2v", "video/x-mpeg");
            fDictionary.Add("m3u", "audio/mpegurl");
            fDictionary.Add("m4e", "video/mpeg4");
            fDictionary.Add("mac", "application/x-mac");
            fDictionary.Add("man", "application/x-troff-man");
            fDictionary.Add("math", "text/xml");
            fDictionary.Add("mdb", "application/msaccess");
            //fDictionary.Add("mdb", "application/x-mdb");
            fDictionary.Add("mfp", "application/x-shockwave-flash");
            fDictionary.Add("mht", "message/rfc822");
            fDictionary.Add("mhtml", "message/rfc822");
            fDictionary.Add("mi", "application/x-mi");
            fDictionary.Add("mid", "audio/mid");
            fDictionary.Add("midi", "audio/mid");
            fDictionary.Add("mil", "application/x-mil");
            fDictionary.Add("mml", "text/xml");
            fDictionary.Add("mnd", "audio/x-musicnet-download");
            fDictionary.Add("mns", "audio/x-musicnet-stream");
            fDictionary.Add("mocha", "application/x-javascript");
            fDictionary.Add("movie", "video/x-sgi-movie");
            fDictionary.Add("mp1", "audio/mp1");
            fDictionary.Add("mp2", "audio/mp2");
            fDictionary.Add("mp2v", "video/mpeg");
            fDictionary.Add("mp3", "audio/mp3");
            fDictionary.Add("mp4", "video/mpeg4");
            fDictionary.Add("mpa", "video/x-mpg");
            fDictionary.Add("mpd", "application/vnd.ms-project");
            fDictionary.Add("mpe", "video/x-mpeg");
            fDictionary.Add("mpeg", "video/mpg");
            fDictionary.Add("mpg", "video/mpg");
            fDictionary.Add("mpga", "audio/rn-mpeg");
            fDictionary.Add("mpp", "application/vnd.ms-project");
            fDictionary.Add("mps", "video/x-mpeg");
            fDictionary.Add("mpt", "application/vnd.ms-project");
            fDictionary.Add("mpv", "video/mpg");
            fDictionary.Add("mpv2", "video/mpeg");
            fDictionary.Add("mpw", "application/vnd.ms-project");
            fDictionary.Add("mpx", "application/vnd.ms-project");
            fDictionary.Add("mtx", "text/xml");
            fDictionary.Add("mxp", "application/x-mmxp");
            fDictionary.Add("net", "image/pnetvue");
            fDictionary.Add("nrf", "application/x-nrf");
            fDictionary.Add("nws", "message/rfc822");
            fDictionary.Add("odc", "text/x-ms-odc");
            fDictionary.Add("out", "application/x-out");
            fDictionary.Add("p10", "application/pkcs10");
            fDictionary.Add("p12", "application/x-pkcs12");
            fDictionary.Add("p7b", "application/x-pkcs7-certificates");
            fDictionary.Add("p7c", "application/pkcs7-mime");
            fDictionary.Add("p7m", "application/pkcs7-mime");
            fDictionary.Add("p7r", "application/x-pkcs7-certreqresp");
            fDictionary.Add("p7s", "application/pkcs7-signature");
            fDictionary.Add("pc5", "application/x-pc5");
            fDictionary.Add("pci", "application/x-pci");
            fDictionary.Add("pcl", "application/x-pcl");
            fDictionary.Add("pcx", "application/x-pcx");
            fDictionary.Add("pdf", "application/pdf");
            //fDictionary.Add("pdf", "application/pdf");
            fDictionary.Add("pdx", "application/vnd.adobe.pdx");
            fDictionary.Add("pfx", "application/x-pkcs12");
            fDictionary.Add("pgl", "application/x-pgl");
            fDictionary.Add("pic", "application/x-pic");
            fDictionary.Add("pko", "application/vnd.ms-pki.pko");
            fDictionary.Add("pl", "application/x-perl");
            fDictionary.Add("plg", "text/html");
            fDictionary.Add("pls", "audio/scpls");
            fDictionary.Add("plt", "application/x-plt");
            //fDictionary.Add("png", "image/png");
            fDictionary.Add("png", "application/x-png");
            fDictionary.Add("pot", "application/vnd.ms-powerpoint");
            fDictionary.Add("ppa", "application/vnd.ms-powerpoint");
            fDictionary.Add("ppm", "application/x-ppm");
            fDictionary.Add("pps", "application/vnd.ms-powerpoint");
            fDictionary.Add("ppt", "application/vnd.ms-powerpoint");
            //fDictionary.Add("ppt", "application/x-ppt");
            fDictionary.Add("pr", "application/x-pr");
            fDictionary.Add("prf", "application/pics-rules");
            fDictionary.Add("prn", "application/x-prn");
            fDictionary.Add("prt", "application/x-prt");
            fDictionary.Add("ps", "application/x-ps");
            //fDictionary.Add("ps", "application/postscript");
            fDictionary.Add("ptn", "application/x-ptn");
            fDictionary.Add("pwz", "application/vnd.ms-powerpoint");
            fDictionary.Add("r3t", "text/vnd.rn-realtext3d");
            fDictionary.Add("ra", "audio/vnd.rn-realaudio");
            fDictionary.Add("ram", "audio/x-pn-realaudio");
            fDictionary.Add("ras", "application/x-ras");
            fDictionary.Add("rat", "application/rat-file");
            fDictionary.Add("rdf", "text/xml");
            fDictionary.Add("rec", "application/vnd.rn-recording");
            fDictionary.Add("red", "application/x-red");
            fDictionary.Add("rgb", "application/x-rgb");
            fDictionary.Add("rjs", "application/vnd.rn-realsystem-rjs");
            fDictionary.Add("rjt", "application/vnd.rn-realsystem-rjt");
            fDictionary.Add("rlc", "application/x-rlc");
            fDictionary.Add("rle", "application/x-rle");
            fDictionary.Add("rm", "application/vnd.rn-realmedia");
            fDictionary.Add("rmf", "application/vnd.adobe.rmf");
            fDictionary.Add("rmi", "audio/mid");
            fDictionary.Add("rmj", "application/vnd.rn-realsystem-rmj");
            fDictionary.Add("rmm", "audio/x-pn-realaudio");
            fDictionary.Add("rmp", "application/vnd.rn-rn_music_package");
            fDictionary.Add("rms", "application/vnd.rn-realmedia-secure");
            fDictionary.Add("rmvb", "application/vnd.rn-realmedia-vbr");
            fDictionary.Add("rmx", "application/vnd.rn-realsystem-rmx");
            fDictionary.Add("rnx", "application/vnd.rn-realplayer");
            fDictionary.Add("rp", "image/vnd.rn-realpix");
            fDictionary.Add("rpm", "audio/x-pn-realaudio-plugin");
            fDictionary.Add("rsml", "application/vnd.rn-rsml");
            fDictionary.Add("rt", "text/vnd.rn-realtext");
            fDictionary.Add("rtf", "application/msword");
            //fDictionary.Add("rtf", "application/x-rtf");
            fDictionary.Add("rv", "video/vnd.rn-realvideo");
            fDictionary.Add("sam", "application/x-sam");
            fDictionary.Add("sat", "application/x-sat");
            fDictionary.Add("sdp", "application/sdp");
            fDictionary.Add("sdw", "application/x-sdw");
            fDictionary.Add("sit", "application/x-stuffit");
            fDictionary.Add("slb", "application/x-slb");
            fDictionary.Add("sld", "application/x-sld");
            fDictionary.Add("slk", "drawing/x-slk");
            fDictionary.Add("smi", "application/smil");
            fDictionary.Add("smil", "application/smil");
            fDictionary.Add("smk", "application/x-smk");
            fDictionary.Add("snd", "audio/basic");
            fDictionary.Add("sol", "text/plain");
            fDictionary.Add("sor", "text/plain");
            fDictionary.Add("spc", "application/x-pkcs7-certificates");
            fDictionary.Add("spl", "application/futuresplash");
            fDictionary.Add("spp", "text/xml");
            fDictionary.Add("ssm", "application/streamingmedia");
            fDictionary.Add("sst", "application/vnd.ms-pki.certstore");
            fDictionary.Add("stl", "application/vnd.ms-pki.stl");
            fDictionary.Add("stm", "text/html");
            fDictionary.Add("sty", "application/x-sty");
            fDictionary.Add("svg", "text/xml");
            fDictionary.Add("swf", "application/x-shockwave-flash");
            fDictionary.Add("tdf", "application/x-tdf");
            fDictionary.Add("tg4", "application/x-tg4");
            fDictionary.Add("tga", "application/x-tga");
            //fDictionary.Add("tif", "image/tiff");
            fDictionary.Add("tif", "application/x-tif");
            fDictionary.Add("tiff", "image/tiff");
            fDictionary.Add("tld", "text/xml");
            fDictionary.Add("top", "drawing/x-top");
            fDictionary.Add("torrent", ");application/x-bittorrent");
            fDictionary.Add("tsd", "text/xml");
            fDictionary.Add("txt", "text/plain");
            fDictionary.Add("uin", "application/x-icq");
            fDictionary.Add("uls", "text/iuls");
            fDictionary.Add("vcf", "text/x-vcard");
            fDictionary.Add("vda", "application/x-vda");
            fDictionary.Add("vdx", "application/vnd.visio");
            fDictionary.Add("vml", "text/xml");
            fDictionary.Add("vpg", "application/x-vpeg005");
            //fDictionary.Add("vsd", "application/vnd.visio");
            fDictionary.Add("vsd", "application/x-vsd");
            fDictionary.Add("vss", "application/vnd.visio");
            //fDictionary.Add("vst", "application/vnd.visio");
            fDictionary.Add("vst", "application/x-vst");
            fDictionary.Add("vsw", "application/vnd.visio");
            fDictionary.Add("vsx", "application/vnd.visio");
            fDictionary.Add("vtx", "application/vnd.visio");
            fDictionary.Add("vxml", "text/xml");
            fDictionary.Add("wav", "audio/wav");
            fDictionary.Add("wax", "audio/x-ms-wax");
            fDictionary.Add("wb1", "application/x-wb1");
            fDictionary.Add("wb2", "application/x-wb2");
            fDictionary.Add("wb3", "application/x-wb3");
            fDictionary.Add("wbmp", "image/vnd.wap.wbmp");
            fDictionary.Add("wiz", "application/msword");
            fDictionary.Add("wk3", "application/x-wk3");
            fDictionary.Add("wk4", "application/x-wk4");
            fDictionary.Add("wkq", "application/x-wkq");
            fDictionary.Add("wks", "application/x-wks");
            fDictionary.Add("wm", "video/x-ms-wm");
            fDictionary.Add("wma", "audio/x-ms-wma");
            fDictionary.Add("wmd", "application/x-ms-wmd");
            fDictionary.Add("wmf", "application/x-wmf");
            fDictionary.Add("wml", "text/vnd.wap.wml");
            fDictionary.Add("wmv", "video/x-ms-wmv");
            fDictionary.Add("wmx", "video/x-ms-wmx");
            fDictionary.Add("wmz", "application/x-ms-wmz");
            fDictionary.Add("wp6", "application/x-wp6");
            fDictionary.Add("wpd", "application/x-wpd");
            fDictionary.Add("wpg", "application/x-wpg");
            fDictionary.Add("wpl", "application/vnd.ms-wpl");
            //fDictionary.Add("wq1", "application/x-wq1");
            fDictionary.Add("wr1", "application/x-wr1");
            fDictionary.Add("wri", "application/x-wri");
            fDictionary.Add("wrk", "application/x-wrk");
            fDictionary.Add("ws", "application/x-ws");
            fDictionary.Add("ws2", "application/x-ws");
            fDictionary.Add("wsc", "text/scriptlet");
            fDictionary.Add("wsdl", "text/xml");
            fDictionary.Add("wvx", "video/x-ms-wvx");
            fDictionary.Add("xdp", "application/vnd.adobe.xdp");
            fDictionary.Add("xdr", "text/xml");
            fDictionary.Add("xfd", "application/vnd.adobe.xfd");
            fDictionary.Add("xfdf", "application/vnd.adobe.xfdf");
            fDictionary.Add("xhtml", "text/html");
            fDictionary.Add("xls", "application/vnd.ms-excel");
            //fDictionary.Add("xls", "application/x-xls");
            fDictionary.Add("xlw", "application/x-xlw");
            fDictionary.Add("xml", "text/xml");
            fDictionary.Add("xpl", "audio/scpls");
            fDictionary.Add("xq", "text/xml");
            fDictionary.Add("xql", "text/xml");
            fDictionary.Add("xquery", "text/xml");
            fDictionary.Add("xsd", "text/xml");
            fDictionary.Add("xsl", "text/xml");
            fDictionary.Add("xslt", "text/xml");
            fDictionary.Add("xwd", "application/x-xwd");
            fDictionary.Add("x_b", "application/x-x_b");
            fDictionary.Add("x_t", "application/x-x_t");
            return fDictionary;            
        }
        
    }
}
